# Copyright (C) 2022 Matt Langston. All Rights Reserved.
"""Constants for fractal governance data analysis"""

from pathlib import Path

import pandas as pd

import fractal_governance

PROJECT_DIR = Path(fractal_governance.__file__).parent.parent
GENESIS_ACCOUNT_STATUS_CSV_PATH = PROJECT_DIR / "data/genesis-account_status.csv"
GENESIS_LATE_CONSENSUS_CSV_PATH = PROJECT_DIR / "data/genesis-late_consensus.csv"
GENESIS_TEAMS_CSV_PATH = PROJECT_DIR / "data/genesis-teams.csv"
GENESIS_WEEKLY_MEASUREMENTS_CSV_PATH = (
    PROJECT_DIR / "data/genesis-weekly_measurements.csv"
)


DATE_OF_FIRST_GENESIS_FRACTAL_MEETING = pd.to_datetime("2/26/2022")

MEETING_ID_WHEN_HIVE_SIGNATURE_REQUIRED = 17
MEETING_ID_WHEN_ADDENDUM_1_GOES_INTO_EFFECT = 23

ACCUMULATED_LEVEL_COLUMN_NAME = "AccumulatedLevel"
ACCUMULATED_RESPECT_COLUMN_NAME = "AccumulatedRespect"
ACCUMULATED_RESPECT_NEW_MEMBER_COLUMN_NAME = "AccumulatedRespectNewMember"
ACCUMULATED_RESPECT_PRO_RATA_COLUMN_NAME = "AccumulatedRespectProRata"
ACCUMULATED_RESPECT_RETURNING_MEMBER_COLUMN_NAME = "AccumulatedRespectReturningMember"
ATTENDANCE_COUNT_COLUMN_NAME = "AttendanceCount"
ATTENDANCE_COUNT_NEW_MEMBER_COLUMN_NAME = "AttendanceCountNewMember"
ATTENDANCE_COUNT_RETURNING_MEMBER_COLUMN_NAME = "AttendanceCountReturningMember"
GROUP_COLUMN_NAME = "Group"
HIVE_ACCOUNT_NAME_COLUMN_NAME = "HiveAccountName"
INDEX_COLUMN_NAME = "Index"
INTEGRAL_COLUMN_NAME = "Integral"
INTEGRAL_END_COLUMN_NAME = "IntegralEnd"
INTEGRAL_START_COLUMN_NAME = "IntegralStart"
LEVEL_COLUMN_NAME = "Level"
MEAN_COLUMN_NAME = "Mean"
MEETING_DATE_COLUMN_NAME = "MeetingDate"
MEETING_ID_COLUMN_NAME = "MeetingID"
MEMBER_ID_COLUMN_NAME = "MemberID"
MEMBER_NAME_COLUMN_NAME = "Name"
NEW_MEMBER_COUNT_COLUMN_NAME = "NewMemberCount"
RESPECT_COLUMN_NAME = "Respect"
RESPECT_PRO_RATA_COLUMN_NAME = "RespectProRata"
RETURNING_MEMBER_COUNT_COLUMN_NAME = "ReturningMemberCount"
ROUND_COLUMN_NAME = "Round"
SIGNATURE_ON_FILE_COLUMN_NAME = "SignatureOnFile"
STANDARD_DEVIATION_COLUMN_NAME = "StandardDeviation"
TEAM_ID_COLUMN_NAME = "TeamID"
TEAM_NAME_COLUMN_NAME = "TeamName"
TIME_COLUMN_NAME = "Time"
TOKENS_INDIVIDUAL = "TokensIndividual"
TOKENS_TEAM = "TokensTeam"
TOKEN_INTEGRAL_COLUMN_NAME = "TokenIntegral"
TOKEN_SUPPLY_AFTER_TRANSITION_TO_CONSTANT_INFLATION_COLUMN_NAME = (
    "TokenSupplyAfterTransitionToConstantInflation"
)
TOKEN_SUPPLY_BEFORE_TRANSITION_TO_CONSTANT_INFLATION_COLUMN_NAME = (
    "TokenSupplyBeforeTransitionToConstantInflation"
)
TOKEN_SUPPLY_COLUMN_NAME = "TokenSupply"
WEIGHTED_MEAN_LEVEL_COLUMN_NAME = "WeightedMeanLevel"
WEIGHTED_MEAN_RESPECT_COLUMN_NAME = "WeightedMeanRespect"
WEIGHTED_MEAN_RESPECT_INDIVIDUAL_FRACTION_PER_MEETING_COLUMN_NAME = (
    f"{WEIGHTED_MEAN_RESPECT_COLUMN_NAME}IndividualFractionPerMeeting"
)
WEIGHTED_MEAN_RESPECT_INDIVIDUAL_PER_MEETING_COLUMN_NAME = (
    f"{WEIGHTED_MEAN_RESPECT_COLUMN_NAME}IndividualPerMeeting"
)
WEIGHTED_MEAN_RESPECT_TEAM_FRACTION_PER_MEETING_COLUMN_NAME = (
    f"{WEIGHTED_MEAN_RESPECT_COLUMN_NAME}TeamFractionPerMeeting"
)
WEIGHTED_MEAN_RESPECT_TEAM_PER_MEETING_COLUMN_NAME = (
    f"{WEIGHTED_MEAN_RESPECT_COLUMN_NAME}TeamPerMeeting"
)
