filegroup(
    name = "csv_files",
    srcs = [
        "genesis-account_status.csv",
        "genesis-late_consensus.csv",
        "genesis-teams.csv",
        "genesis-weekly_measurements.csv",
    ],
    visibility = ["//visibility:public"],
)
